version: "3.8"

services:
  postgres:
    image: postgres:17.3-alpine3.21
    container_name: postgres-even-up
    ports:
      - "5440:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "GGzS6AJHsArdm_tSn_H0"
      POSTGRES_DB: "even-up-db"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d even-up-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - even-up-network

networks:
  even-up-network:
    driver: bridge